### ISSUE TITLE
哥哥，jd_necklacecard报错了~

### ISSUE THREAD

**Issue by nomoneynolife** [danteswx/fxxk#2]
获取活动成功，已有卡片【5】张，总共需要卡片【6】张
任务：签到任务，去执行
{"rtn_code":403,"rtn_msg":"非法请求！"}

**Comment by danteswx** [comment]
大部分账号都log加密了，手动做吧。

**Comment by nomoneynolife** [comment]
> 大部分账户都记录了，手动做吧。

明白了~
